// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userservice.proto

package userservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginResponse_LoginStatus int32

const (
	LoginResponse_SUCCESS             LoginResponse_LoginStatus = 0
	LoginResponse_INVALID_CREDENTIALS LoginResponse_LoginStatus = 1
	LoginResponse_NOT_ACTIVATED       LoginResponse_LoginStatus = 2
)

var LoginResponse_LoginStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "INVALID_CREDENTIALS",
	2: "NOT_ACTIVATED",
}

var LoginResponse_LoginStatus_value = map[string]int32{
	"SUCCESS":             0,
	"INVALID_CREDENTIALS": 1,
	"NOT_ACTIVATED":       2,
}

func (x LoginResponse_LoginStatus) String() string {
	return proto.EnumName(LoginResponse_LoginStatus_name, int32(x))
}

func (LoginResponse_LoginStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{3, 0}
}

type ActivateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateUserRequest) Reset()         { *m = ActivateUserRequest{} }
func (m *ActivateUserRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateUserRequest) ProtoMessage()    {}
func (*ActivateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{0}
}

func (m *ActivateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateUserRequest.Unmarshal(m, b)
}
func (m *ActivateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateUserRequest.Marshal(b, m, deterministic)
}
func (m *ActivateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateUserRequest.Merge(m, src)
}
func (m *ActivateUserRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateUserRequest.Size(m)
}
func (m *ActivateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateUserRequest proto.InternalMessageInfo

func (m *ActivateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ActivateUserResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateUserResponse) Reset()         { *m = ActivateUserResponse{} }
func (m *ActivateUserResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateUserResponse) ProtoMessage()    {}
func (*ActivateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{1}
}

func (m *ActivateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateUserResponse.Unmarshal(m, b)
}
func (m *ActivateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateUserResponse.Marshal(b, m, deterministic)
}
func (m *ActivateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateUserResponse.Merge(m, src)
}
func (m *ActivateUserResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateUserResponse.Size(m)
}
func (m *ActivateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateUserResponse proto.InternalMessageInfo

func (m *ActivateUserResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ActivateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoginRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// Types that are valid to be assigned to UserCredential:
	//	*LoginRequest_Username
	//	*LoginRequest_Email
	UserCredential       isLoginRequest_UserCredential `protobuf_oneof:"userCredential"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type isLoginRequest_UserCredential interface {
	isLoginRequest_UserCredential()
}

type LoginRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*LoginRequest_Username) isLoginRequest_UserCredential() {}

func (*LoginRequest_Email) isLoginRequest_UserCredential() {}

func (m *LoginRequest) GetUserCredential() isLoginRequest_UserCredential {
	if m != nil {
		return m.UserCredential
	}
	return nil
}

func (m *LoginRequest) GetUsername() string {
	if x, ok := m.GetUserCredential().(*LoginRequest_Username); ok {
		return x.Username
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if x, ok := m.GetUserCredential().(*LoginRequest_Email); ok {
		return x.Email
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoginRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoginRequest_Username)(nil),
		(*LoginRequest_Email)(nil),
	}
}

type LoginResponse struct {
	Status               LoginResponse_LoginStatus `protobuf:"varint,1,opt,name=status,proto3,enum=userservice.LoginResponse_LoginStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() LoginResponse_LoginStatus {
	if m != nil {
		return m.Status
	}
	return LoginResponse_SUCCESS
}

func init() {
	proto.RegisterEnum("userservice.LoginResponse_LoginStatus", LoginResponse_LoginStatus_name, LoginResponse_LoginStatus_value)
	proto.RegisterType((*ActivateUserRequest)(nil), "userservice.ActivateUserRequest")
	proto.RegisterType((*ActivateUserResponse)(nil), "userservice.ActivateUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "userservice.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "userservice.LoginResponse")
}

func init() {
	proto.RegisterFile("userservice.proto", fileDescriptor_68a7ca558839fd2b)
}

var fileDescriptor_68a7ca558839fd2b = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x5b, 0x0c, 0x08, 0x53, 0x20, 0x65, 0x21, 0x88, 0xc4, 0x03, 0xee, 0xc1, 0x78, 0x91,
	0x03, 0xde, 0x4d, 0x6a, 0x5b, 0x63, 0x13, 0x82, 0x49, 0x5b, 0xb8, 0x92, 0x0a, 0x13, 0xd3, 0x04,
	0x5a, 0xdc, 0x5d, 0xf0, 0xa7, 0xf8, 0x1f, 0xfc, 0x95, 0xa6, 0xbb, 0x85, 0xb4, 0x09, 0x7a, 0x7c,
	0xd3, 0x2f, 0xf3, 0xde, 0xbc, 0x2e, 0x74, 0xf6, 0x1c, 0x19, 0x47, 0x76, 0x88, 0x57, 0x38, 0xde,
	0xb1, 0x54, 0xa4, 0xc4, 0x28, 0x8c, 0xe8, 0x03, 0x74, 0xad, 0x95, 0x88, 0x0f, 0x91, 0xc0, 0x39,
	0x47, 0xe6, 0xe3, 0xe7, 0x1e, 0xb9, 0x20, 0x7d, 0xa8, 0x65, 0x94, 0xb7, 0x1e, 0xe8, 0x23, 0xfd,
	0xbe, 0xe1, 0xe7, 0x8a, 0x3a, 0xd0, 0x2b, 0xe3, 0x7c, 0x97, 0x26, 0x1c, 0x33, 0x9e, 0x8b, 0x48,
	0xec, 0xb9, 0xe4, 0xeb, 0x7e, 0xae, 0x48, 0x0f, 0xaa, 0xc8, 0x58, 0xca, 0x06, 0x15, 0xb9, 0x46,
	0x09, 0xca, 0xa0, 0x39, 0x4d, 0x3f, 0xe2, 0xe4, 0xe8, 0x36, 0x84, 0xfa, 0x2e, 0xe2, 0xfc, 0x2b,
	0x65, 0x47, 0xbf, 0x93, 0x26, 0x37, 0x50, 0xcf, 0xbc, 0x93, 0x68, 0x8b, 0x6a, 0xc9, 0xab, 0xe6,
	0x9f, 0x26, 0xa4, 0x0f, 0x55, 0xdc, 0x46, 0xf1, 0x66, 0x70, 0x91, 0x7f, 0x52, 0xf2, 0xd9, 0x84,
	0x76, 0xc6, 0xd8, 0x0c, 0xd7, 0x98, 0x88, 0x38, 0xda, 0xd0, 0x6f, 0x1d, 0x5a, 0xb9, 0x69, 0x9e,
	0xf9, 0xa9, 0x94, 0xb9, 0x3d, 0xb9, 0x1b, 0x17, 0xbb, 0x2a, 0xb1, 0x4a, 0x05, 0x92, 0x3e, 0xde,
	0x46, 0x5f, 0xc0, 0x28, 0x8c, 0x89, 0x01, 0x97, 0xc1, 0xdc, 0xb6, 0xdd, 0x20, 0x30, 0x35, 0x72,
	0x05, 0x5d, 0x6f, 0xb6, 0xb0, 0xa6, 0x9e, 0xb3, 0xb4, 0x7d, 0xd7, 0x71, 0x67, 0xa1, 0x67, 0x4d,
	0x03, 0x53, 0x27, 0x1d, 0x68, 0xcd, 0xde, 0xc2, 0xa5, 0x65, 0x87, 0xde, 0xc2, 0x0a, 0x5d, 0xc7,
	0xac, 0x4c, 0x7e, 0x74, 0x30, 0xb2, 0x32, 0x03, 0xe5, 0x4c, 0xe6, 0xd0, 0x2c, 0x76, 0x4c, 0x46,
	0xa5, 0x5c, 0x67, 0xfe, 0xd6, 0xf0, 0xf6, 0x1f, 0x42, 0x1d, 0x40, 0x35, 0xe2, 0x40, 0x43, 0xc6,
	0x95, 0x3b, 0xaf, 0xcf, 0xdd, 0xaa, 0x96, 0x0d, 0xff, 0xae, 0x81, 0x6a, 0xef, 0x35, 0xf9, 0x86,
	0x1e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x92, 0xc7, 0xaa, 0x0c, 0x58, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*ActivateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*ActivateUserResponse, error) {
	out := new(ActivateUserResponse)
	err := c.cc.Invoke(ctx, "/userservice.UserService/ActivateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/userservice.UserService/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ActivateUser(context.Context, *ActivateUserRequest) (*ActivateUserResponse, error)
	LoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) ActivateUser(ctx context.Context, req *ActivateUserRequest) (*ActivateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateUser not implemented")
}
func (*UnimplementedUserServiceServer) LoginUser(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ActivateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ActivateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userservice.UserService/ActivateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ActivateUser(ctx, req.(*ActivateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userservice.UserService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userservice.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateUser",
			Handler:    _UserService_ActivateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UserService_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userservice.proto",
}
